apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: ee-ambulance-ufe-content
spec:
  microFrontend: ee-ambulance-ufe
  element: ee-ambulance-wl-app
  displayRules:
    - allOf:
        - context-name: main-content
        - path: "^(\\.?/)?ee-ambulance-wl(/.*)?$"